from __future__ import annotations

import logging

from fastapi import Body, FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse

from app.config import Settings, get_settings
from app.directives import DirectiveValidationError, compile_constraints, validate_interpretations
from app.interpreter import InterpretationProvider, InterpretationProviderError, OpenAIInterpreter
from app.models import ErrorResponse, OptimizationRequest, OptimizationResponse
from app.optimizer import OptimizationError, optimize_schedule
from app.replay import ReplayValidationError, replay_plan

OPENAPI_DESCRIPTION = """\
Optimize a campus's 24-hour electricity cost while satisfying hourly demand, solar availability, battery limits, and
validated operator constraints.

### How a request is processed

1. **Validate** the exact 24-hour input contract.
2. **Interpret** one to three untrusted operator notes with a structured-output LLM.
3. **Validate deterministically** that each interpretation is one of the allowed directive types.
4. **Optimize** the schedule with a linear program, then independently replay every constraint before returning JSON.

The LLM never chooses the schedule and has no tools. Time windows use a 24-hour clock, are start-inclusive and
end-exclusive, and a solar-reduction factor means the usable fraction **remaining** (for example, 80% reduction = 0.2).
"""

OPENAPI_REQUEST_EXAMPLE = {
    "scenario_id": "swagger-demo",
    "operator_notes": [
        "Rooftop panels are being cleaned from noon until 2 PM; only 25% of the forecast solar is usable then.",
        "Keep at least 50 kWh in the battery between 6 PM and 9 PM.",
    ],
    "hours": [
        {
            "hour": hour,
            "demand_kwh": 180.0,
            "solar_kwh": 45.0 if 8 <= hour <= 16 else 0.0,
            "tariff_bdt_per_kwh": 9.5 if 18 <= hour <= 22 else 6.5,
        }
        for hour in range(24)
    ],
    "battery": {
        "capacity_kwh": 200.0,
        "initial_energy_kwh": 100.0,
        "minimum_energy_kwh": 30.0,
        "max_charge_kwh_per_hour": 50.0,
        "max_discharge_kwh_per_hour": 50.0,
    },
}

OPTIMIZE_REQUEST_BODY = Body(
    openapi_examples={
        "two_directives": {
            "summary": "Solar reduction and evening battery reserve",
            "description": "A complete valid 24-hour request with two notes that require LLM interpretation.",
            "value": OPENAPI_REQUEST_EXAMPLE,
        }
    }
)


def _summary(interpreted_count: int, response: OptimizationResponse) -> str:
    if interpreted_count:
        directive_text = (
            f"Applied {interpreted_count} operator directive(s) after deterministic validation"
        )
    else:
        directive_text = "No operator-note constraints applied after deterministic validation"
    return (
        f"{directive_text}; optimized grid cost is {response.total_cost_bdt:.2f} BDT "
        f"with peak grid use {response.peak_grid_kwh:.2f} kWh."
    )


def _interpret_and_validate(
    provider: InterpretationProvider, payload: OptimizationRequest, semantic_retries: int
):
    """Accept only deterministic-valid output, with one bounded LLM repair opportunity."""
    candidates = provider.interpret(payload)
    for attempt in range(semantic_retries + 1):
        try:
            return validate_interpretations(candidates, payload)
        except DirectiveValidationError as error:
            repair = getattr(provider, "repair", None)
            if attempt == semantic_retries or not callable(repair):
                raise
            # Error strings are generated by local validation only and contain no operator-note text.
            candidates = repair(payload, str(error))
    raise AssertionError("semantic retry loop must return or raise")  # pragma: no cover


def create_app(
    settings: Settings | None = None,
    interpreter: InterpretationProvider | None = None,
) -> FastAPI:
    settings = settings or get_settings()
    logging.basicConfig(level=settings.log_level.upper())

    app = FastAPI(
        title="GridWise LLM Energy Optimizer",
        version="0.1.0",
        description=OPENAPI_DESCRIPTION,
        contact={"name": "Infinity Loop SEU"},
        openapi_tags=[
            {
                "name": "Service health",
                "description": "Readiness endpoint used by the judging harness and deployment probes.",
            },
            {
                "name": "Energy optimization",
                "description": "LLM-assisted directive interpretation with deterministic optimization and replay validation.",
            },
        ],
        docs_url="/docs",
        redoc_url=None,
        swagger_ui_parameters={"defaultModelsExpandDepth": 1, "displayRequestDuration": True},
    )
    app.state.settings = settings
    app.state.interpreter = interpreter

    @app.exception_handler(RequestValidationError)
    async def invalid_request_handler(_: Request, __: RequestValidationError) -> JSONResponse:
        return JSONResponse(
            status_code=400,
            content={"detail": "malformed or structurally invalid request"},
        )

    @app.get(
        "/health",
        response_model=dict[str, str],
        summary="Check service readiness",
        description="Returns 200 as soon as this API process is ready to accept requests. It does not call the LLM.",
        response_description="The service is ready.",
        operation_id="getHealth",
        tags=["Service health"],
        responses={
            200: {
                "description": "The service is ready.",
                "content": {"application/json": {"example": {"status": "ok"}}},
            },
            500: {"model": ErrorResponse, "description": "Unexpected service failure."},
        },
    )
    def health() -> dict[str, str]:
        return {"status": "ok"}

    @app.post(
        "/optimize-energy",
        response_model=OptimizationResponse,
        summary="Interpret notes and optimize a 24-hour energy plan",
        description=(
            "Accepts exactly 24 hourly records and one to three operator notes. The response contains a structured "
            "interpretation for every note and a feasible least-cost plan. Returned totals are recomputed from the "
            "hourly plan before the response is sent."
        ),
        response_description="Replay-validated 24-hour optimization result.",
        operation_id="optimizeEnergy",
        tags=["Energy optimization"],
        responses={
            400: {
                "model": ErrorResponse,
                "description": "Malformed JSON or a request that does not match the exact input contract.",
            },
            422: {
                "model": ErrorResponse,
                "description": "The scenario is infeasible under the validated constraints.",
            },
            500: {
                "model": ErrorResponse,
                "description": "Controlled provider, interpretation, or internal validation failure. No secrets are exposed.",
            },
        },
    )
    def optimize_energy(
        payload: OptimizationRequest = OPTIMIZE_REQUEST_BODY,
    ) -> OptimizationResponse:
        provider = app.state.interpreter
        if provider is None:
            try:
                provider = OpenAIInterpreter(app.state.settings)
                app.state.interpreter = provider
            except InterpretationProviderError as error:
                raise HTTPException(
                    status_code=500, detail="language-model configuration is unavailable"
                ) from error

        try:
            directives = _interpret_and_validate(
                provider, payload, app.state.settings.llm_semantic_retries
            )
        except InterpretationProviderError as error:
            raise HTTPException(
                status_code=500, detail="language-model interpretation failed safely"
            ) from error
        except DirectiveValidationError as error:
            raise HTTPException(
                status_code=500, detail="language-model output failed deterministic validation"
            ) from error

        constraints = compile_constraints(payload, directives)
        try:
            result = optimize_schedule(payload, constraints)
        except OptimizationError as error:
            raise HTTPException(
                status_code=422, detail="scenario is infeasible under the declared constraints"
            ) from error

        try:
            total_grid, total_cost, peak_grid = replay_plan(
                payload, constraints, result.hourly_plan
            )
        except (
            ReplayValidationError
        ) as error:  # A code defect or numerical regression; never return unsafe output.
            raise HTTPException(
                status_code=500, detail="internal schedule validation failed"
            ) from error

        response = OptimizationResponse(
            scenario_id=payload.scenario_id,
            directive_interpretation=directives,
            hourly_plan=result.hourly_plan,
            total_grid_kwh=total_grid,
            total_cost_bdt=total_cost,
            peak_grid_kwh=peak_grid,
            plan_summary="",
        )
        response.plan_summary = _summary(sum(item.applies for item in directives), response)
        return response

    return app


app = create_app()
